spring:
  application:
    name: hello-spring-cloud-zuul
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    servlet:
#      content-type: text/html
#    encoding: UTF-8

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign