spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
    encoding: UTF-8

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/